package com.si400.recargacarro.view;

import com.si400.recargacarro.model.Address;
import com.si400.recargacarro.model.Location;
import com.si400.recargacarro.model.Stations;
import com.si400.recargacarro.model.StationsTableModel;
import com.si400.recargacarro.model.User;
import javafx.application.Platform;
import javafx.embed.swing.JFXPanel;
import javafx.scene.Scene;
import javafx.scene.chart.BarChart;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import static javax.swing.JOptionPane.showMessageDialog;

/*
    UNICAMP - Faculdade de Tecnologia
    Disciplina SI400 - Programação Orientada a Objetos II (2016)

    Autores:
    Ricardo Favero       157161
    Fernanda Gravena     159702
    Isadora Fonseca      155815
    Marcela Magossi      156521 
 */

public class MainFrame extends javax.swing.JFrame {

    User u = new User();
    Stations allStations = new Stations();

    static String[] states = new String[]{
        "", "Alabama", "Alaska", "Arizona", "Arkansas", "California",
        "Colorado", "Connecticut", "Delaware", "Florida", "Georgia",
        "Hawaii", "Idaho", "Illinois", "Indiana", "Iowa", "Kansas",
        "Kentucky", "Louisiana", "Maine", "Maryland", "Massachusetts",
        "Michigan", "Minnesota", "Mississippi", "Missouri", "Montana",
        "Nebraska", "Nevada", "New Hampshire", "New Jersey", "New Mexico",
        "New York", "North Carolina", "North Dakota", "Ohio", "Oklahoma",
        "Oregon", "Pennsylvania", "Rhode Island", "South Carolina", "South Dakota",
        "Tennessee", "Texas", "Utah", "Vermont", "Virginia", "Washington", "West Virginia",
        "Wisconsin", "Wyoming"
    };

    /**
     * Creates new form JFrame
     */
    public MainFrame() {
        initComponents();
        Stations x = new Stations();
        showDataOnTable(x);
        allStations.readStream();

        /*
        // TEST: creating list of stations
        Stations test = new Stations();
        test.readStream();
        //System.out.println(test);

        // TEST: getting coordinates from address
        Address a = new Address(
        "3241 S Wabash Ave",
        "Chicago",
        "IL",
        "60616"
        );
        Location l1 = a.getGoogleLocation();
        //System.out.println(l1);
        
        // TEST: getting distance between coordinates
        Location l2 = new Location();
        l2.setLatitude(29.7545795);
        l2.setLongitude(-95.3724258);
        //System.out.println("Distance in meters (google): " + l2.getGoogleDistanceTo(l1));
        //System.out.println("Distance in meters: " + Location.getDistance(l1, l2));
        
        User u = new User("Ricardo", l1);
        int radius = 50; // in miles
        Stations result = u.getStationsInRadius(test, radius); 
        System.out.println("\nFound " + result.getStations().size() + " stations in a " + radius/1000 + " km radius from " + a + "\n");
        System.out.println(result);
        
        //jTableResults.setAutoResizeMode( JTable.AUTO_RESIZE_OFF );
        //jTableResults.setSize(500, 500);
        //jTableResults.setRowHeight(30);
        //jTableResults.getColumnModel().getColumn(2).setMinWidth(6);
         apresentarDadosNaTabelav2(result);
         */
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanellSearch = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableResults = new javax.swing.JTable();
        radiusSlider = new javax.swing.JSlider();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        radiusLabel = new javax.swing.JLabel();
        searchButton = new javax.swing.JButton();
        streetField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cityField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        stateComboBox = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        zipField = new javax.swing.JTextField();
        jPanelStatistics = new javax.swing.JPanel();
        chart1Button = new javax.swing.JButton();
        chart2Button = new javax.swing.JButton();
        chart3Button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(null);
        setResizable(false);

        jTableResults.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableResults);

        radiusSlider.setMaximum(50);
        radiusSlider.setMinimum(1);
        radiusSlider.setValue(25);
        radiusSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                radiusSliderStateChanged(evt);
            }
        });

        jLabel1.setText("Street Address: ");

        jLabel2.setText("Search radius:");

        radiusLabel.setText("25 miles");

        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        streetField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                streetFieldKeyTyped(evt);
            }
        });

        jLabel3.setText("City: ");

        cityField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cityFieldKeyTyped(evt);
            }
        });

        jLabel4.setText("State:");

        stateComboBox.setModel(new DefaultComboBoxModel(states));
        stateComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                stateComboBoxItemStateChanged(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel5.setText("OR");

        jLabel6.setText("ZIP Code:");

        zipField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                zipFieldKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanellSearchLayout = new javax.swing.GroupLayout(jPanellSearch);
        jPanellSearch.setLayout(jPanellSearchLayout);
        jPanellSearchLayout.setHorizontalGroup(
            jPanellSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1307, Short.MAX_VALUE)
            .addGroup(jPanellSearchLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanellSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanellSearchLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(zipField, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanellSearchLayout.createSequentialGroup()
                        .addGap(271, 271, 271)
                        .addComponent(jLabel5)
                        .addGap(67, 67, 67)
                        .addGroup(jPanellSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanellSearchLayout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addGroup(jPanellSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGroup(jPanellSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanellSearchLayout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(stateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanellSearchLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cityField, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanellSearchLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(streetField, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanellSearchLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(radiusSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(radiusLabel))
                    .addComponent(searchButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanellSearchLayout.setVerticalGroup(
            jPanellSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanellSearchLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanellSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(streetField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(zipField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanellSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cityField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanellSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(stateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(jPanellSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(radiusSlider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(radiusLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(42, 42, 42)
                .addComponent(searchButton)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Search for Stations", jPanellSearch);

        chart1Button.setText("Number of Stations by State");
        chart1Button.setToolTipText("");
        chart1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chart1ButtonActionPerformed(evt);
            }
        });

        chart2Button.setText("Top 10 Cities by Number of Stations");
        chart2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chart2ButtonActionPerformed(evt);
            }
        });

        chart3Button.setText("Number of Stations by Region");
        chart3Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chart3ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelStatisticsLayout = new javax.swing.GroupLayout(jPanelStatistics);
        jPanelStatistics.setLayout(jPanelStatisticsLayout);
        jPanelStatisticsLayout.setHorizontalGroup(
            jPanelStatisticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelStatisticsLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanelStatisticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(chart3Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(chart1Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(chart2Button, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(609, Short.MAX_VALUE))
        );
        jPanelStatisticsLayout.setVerticalGroup(
            jPanelStatisticsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelStatisticsLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(chart1Button, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(chart2Button, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(chart3Button, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(255, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Charts", null, jPanelStatistics, "");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );

        jTabbedPane2.getAccessibleContext().setAccessibleName("Search for Stations");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void zipFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_zipFieldKeyTyped
        // TODO add your handling code here:
        streetField.setText("");
        cityField.setText("");
        stateComboBox.setSelectedItem("");
    }//GEN-LAST:event_zipFieldKeyTyped

    private void stateComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_stateComboBoxItemStateChanged
        // TODO add your handling code here:
        zipField.setText("");
    }//GEN-LAST:event_stateComboBoxItemStateChanged

    private void cityFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cityFieldKeyTyped
        // TODO add your handling code here:
        zipField.setText("");
    }//GEN-LAST:event_cityFieldKeyTyped

    private void streetFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_streetFieldKeyTyped
        // TODO add your handling code here:
        zipField.setText("");
    }//GEN-LAST:event_streetFieldKeyTyped

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        if (!zipField.getText().equals("") || !streetField.getText().equals("") && !cityField.getText().equals("") && !stateComboBox.getSelectedItem().equals("")) {
            Address a = new Address(streetField.getText(), cityField.getText(), stateComboBox.getSelectedItem().toString(), zipField.getText());
            Location l = a.getGoogleLocation();
            u.setLocation(l);
            Stations result = u.getStationsInRadius(allStations, radiusSlider.getValue());
            showDataOnTable(result);
        } else if (zipField.getText().equals("")) {
            if (streetField.getText().equals("") && cityField.getText().equals("") && stateComboBox.getSelectedItem().equals("")) {
                showMessageDialog(null, "Please enter an address or ZIP Code!");
            } else if (streetField.getText().equals("")) {
                showMessageDialog(null, "Please enter a street address!");
            } else if (cityField.getText().equals("")) {
                showMessageDialog(null, "Please enter a city!");
            } else if (stateComboBox.getSelectedItem().equals("")) {
                showMessageDialog(null, "Please enter a state!");
            }
        }

    }//GEN-LAST:event_searchButtonActionPerformed

    private void radiusSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_radiusSliderStateChanged
        radiusLabel.setText(radiusSlider.getValue() + " miles");
    }//GEN-LAST:event_radiusSliderStateChanged

    private void chart1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chart1ButtonActionPerformed
        JFrame frame = new JFrame("Number of Stations by State");
        frame.setSize(1300, 800);

        final JFXPanel fxPanelB = new JFXPanel();
        frame.add(fxPanelB);

        Platform.runLater(new Runnable() {
            @Override
            public void run() {
                StatesChart linesample = new StatesChart();
                BarChart<String, Number> chart = linesample.getChart(allStations);

                Scene scene = new Scene(chart, 800, 600);
                fxPanelB.setScene(scene);

                frame.setVisible(true);
            }
        });
    }//GEN-LAST:event_chart1ButtonActionPerformed

    private void chart2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chart2ButtonActionPerformed
        JFrame frame = new JFrame("Top 10 Cities by Number of Stations");
        frame.setSize(1300, 800);

        final JFXPanel fxPanelB = new JFXPanel();
        frame.add(fxPanelB);

        Platform.runLater(new Runnable() {
            @Override
            public void run() {

                CitiesChart linesample = new CitiesChart();
                BarChart<Number, String> chart = linesample.getChart(allStations);

                Scene scene = new Scene(chart, 800, 600);
                fxPanelB.setScene(scene);

                frame.setVisible(true);
            }
        });
    }//GEN-LAST:event_chart2ButtonActionPerformed

    private void chart3ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chart3ButtonActionPerformed
        JFrame frame = new JFrame("Number of Stations by Region");
        frame.setSize(1300, 800);

        final JFXPanel fxPanelB = new JFXPanel();
        frame.add(fxPanelB);

        Platform.runLater(new Runnable() {
            @Override
            public void run() {

                RegionsChart linesample = new RegionsChart();
                BarChart<Number, String> chart = linesample.getChart(allStations);

                Scene scene = new Scene(chart, 800, 600);
                fxPanelB.setScene(scene);

                frame.setVisible(true);
            }
        });
    }//GEN-LAST:event_chart3ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new MainFrame().setVisible(true);

            }
        });
    }

    private void showDataOnTable(Stations list) {
        this.jTableResults.setModel(new StationsTableModel(list));
        jTableResults.getColumnModel().getColumn(2).setPreferredWidth(200);
        jTableResults.getColumnModel().getColumn(5).setPreferredWidth(20);
        //this.jTableResults.setco
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton chart1Button;
    private javax.swing.JButton chart2Button;
    private javax.swing.JButton chart3Button;
    private javax.swing.JTextField cityField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanelStatistics;
    private javax.swing.JPanel jPanellSearch;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable jTableResults;
    private javax.swing.JLabel radiusLabel;
    private javax.swing.JSlider radiusSlider;
    private javax.swing.JButton searchButton;
    private javax.swing.JComboBox<String> stateComboBox;
    private javax.swing.JTextField streetField;
    private javax.swing.JTextField zipField;
    // End of variables declaration//GEN-END:variables
}
